[package]
name = "euler"
version = "0.1.0"
edition = "2021"

[dependencies]
num-bigint = "0.4"
num-rational = "0.4"
rayon = "1.10.0"
num-traits = "0.2.15"

[profile.release]
lto = true
opt-level = 3
codegen-units = 1
panic = "abort"

